[package]
name = "fn-search-backend"
version = "0.1.0"
authors = ["Andrew Houts <ahouts4@gmail.com>"]

[dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
toml = {version = "0.4.8", default-features = false, features = ["serde"] }
