[package]
name = "scrape"
version = "0.1.0"
authors = ["ahouts <ahouts4@gmail.com>"]

[dependencies]
reqwest = "0.9.4"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
rayon = "1.0.2"
clap = "2.32.0"
