[package]
name = "db"
version = "0.1.0"
authors = ["Andrew Houts <ahouts4@gmail.com>"]

[dependencies]
diesel = { version = "1.3.3", features = ["postgres"] }
diesel_migrations = { version = "1.3.0", features = ["postgres"] }
fn-search-backend = { path = ".." }
clap = "2.32.0"
